name: PR Check Pipeline

on:
    pull_request:
        branches:
            - dev

permissions:
    contents: read
    issues: read
    checks: write
    pull-requests: write

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:

    test-and-report:
        runs-on:
            group: landra-infra
        steps:
            - uses: actions/checkout@v5
            - uses: landra-sistemas/ci-templates/node/test-report@main
              with:
                  node-version: 20

    security-scan:
        runs-on:
            group: landra-infra
        steps:
            - uses: actions/checkout@v5
            ## Workaround for sbom generation issues

            - uses: landra-sistemas/ci-templates/node/setup-env@main
              with:
                  node-version: 20
            - uses: landra-sistemas/ci-templates/common/security-scan@main
              with:
                  fail-build: false
                  severity-cutoff: "high"

    extras:
        needs: security-scan
        runs-on:
            group: landra-infra
        steps:
            - shell: bash
              run: |
                  if [ "${{ github.event_name }}" == "push" ]; then
                      echo "depth=$(($(jq length <<< '${{ toJson(github.event.commits) }}') + 2))" >> $GITHUB_ENV
                      echo "branch=${{ github.ref_name }}" >> $GITHUB_ENV
                  fi
                  if [ "${{ github.event_name }}" == "pull_request" ]; then
                      echo "depth=$((${{ github.event.pull_request.commits }}+2))" >> $GITHUB_ENV
                      echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
                  fi
            - uses: actions/checkout@v5
              with:
                  ref: ${{env.branch}}
                  fetch-depth: ${{env.depth}}

            - name: Secret scan
              uses: landra-sistemas/ci-templates/common/secret-scan@main
